services:
  api:
    container_name: quiz_test_api
    environment:
      - DB_NAME=quiz_test
      - DB_CONNECTION=mongodb://user:password@db:27017
      - PORT=5000
    depends_on:
      - db
    tty: true
  db:
    container_name: quiz_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=quiz_test
volumes:
  test_db:
networks:
  default:
    name: quiz_test
